#!/bin/bash

SQL="${SQL} DECLARE "
SQL="${SQL} TYPE order_id IS TABLE OF NUMBER(10,0); "
SQL="${SQL} TYPE order_name IS TABLE OF VARCHAR2(50); "
SQL="${SQL} TYPE cities IS TABLE OF VARCHAR2(50); "
SQL="${SQL} orderId order_id; "
SQL="${SQL} orderName order_name; "
SQL="${SQL} city cities; "
SQL="${SQL} BEGIN "
SQL="${SQL} SELECT customer_id, customer_name, city BULK COLLECT INTO orderId, orderName, city "
SQL="${SQL} FROM ABC.customers; "
SQL="${SQL} FORALL idx IN 1..orderId.COUNT "
SQL="${SQL} INSERT ALL "
SQL="${SQL} INTO ABCDEF.orders VALUES (orderId(idx), orderName(idx), city(idx)) "
SQL="${SQL} INTO ABCDEF.shipers VALUES (orderId(idx), orderName(idx), city(idx)) "
SQL="${SQL} SELECT * FROM dual; "
SQL="${SQL} END; "